### ISSUE TITLE
Error using the -r flag

### ISSUE THREAD

**Issue by Dageus** [Achno/gowall#17]
OS: Linux
Distro: Arch Linux 6.11.6
Terminal Emulator: Alacritty
Shell: zsh

Installed from AUR.

command:
```bash
➜  ~ gowall convert ~/Pictures/Wallpapers/wallpaper.vagabond.jpg -r #312424,#1D1C2D
Error: flag needs an argument: 'r' in -r
Usage:
  gowall convert [image path / batch flag] [flags]

Flags:
  -b, --batch strings     Usage: --batch file1.png,file2.png ...
  -f, --format string     Usage: --format [Extension]
  -h, --help              help for convert
  -r, --replace strings   Usage: --replace #FromColor,#ToColor
  -t, --theme string      Usage : --theme [ThemeName] (default "catppuccin")
```

I was wondering if I used the command wrong, but it seems correct according to the usage in the readme,

**Comment by Dageus** [comment]
Error also occurs if I build from source.

**Comment by Achno** [comment]
Im also using Alacritty and zsh with the AUR version and i cant  reproduce it. Can you upload the image `wallpaper.vagabond.jpg` ?

**Comment by Dageus** [comment]
image:
![wallpaper vagabond](https://github.com/user-attachments/assets/8be35b89-eb42-4202-9e66-882017067012)

i have the zsh-autosuggestions, I don't know if that's what you're referring to

**Comment by Achno** [comment]
I think your shell might be intercepting the `#` delimiter for some reason thats the reason why it would print  `flag needs an argument: 'r' in -r` because there isn't anything after `-r`

Try putting `" "` around the colors:

`gowall convert ~/Pictures/Wallpapers/wallpaper.vagabond.jpg -r "#312424,#1D1C2D" `

(obviously your image does not contain the `312424` color but you get the point)

**Comment by Dageus** [comment]
yeah when I put it in quotes it worked, thanks man!

**Comment by Achno** [comment]
@Dageus  No problem, though another thing i noticed is that even though the color pickers say that the background black color in the image is `#171717` probably because of the conversion of the image to rgb points there are very small discrepancies and that color becomes something else like `#171719`.

So when i try to look for `#171717` in the image it doesn't really exist.

I will have to revise the algorithm used and relax the constraints so it doesn't have to be `that exact pixel`. So what im saying is if you get too many 

```bash
Error Processing Image: while processing image : replacing color failed : the color : #171717 was not found in the image,nothing to replace
```
dont get discouraged i will fix it within this week i hope

**Comment by Achno** [comment]
Okay good news i relaxed the constraints a bit and now it matches the colors : https://freeimage.host/i/2RWzIfI here is your previous image with the background turned purple so you can see the difference.

**Comment by Dageus** [comment]
You're blazing fast man! thanks for the quick update
